[FilterPlugin]
; This file lists additional files which will be packaged along with your plugin.
; Paths should be listed in the form:
; /Path/To/File.ext

; Python scripts
/Python/...

; Content
/Content/...
